##############
# Executors #
##############
executors:
  localtest:
    docker:
      - image: circleci/node:10.15.0

version: 2.1

##############
# workflows  #
##############
workflows:
  build-deploy:
    jobs:
      - test

orbs:
  slack: circleci/slack@3.2.0

jobs:
  test:
    executor: localtest
    steps:
      - checkout
      - run:
          name: install deps
          command: npm install
      - run:
          name: install ganache
          command: npm install ganache-cli mocha mocha-junit-reporter
      - run:
          name: Run up local chain
          command: npx ganache-cli -h 127.0.0.1 -p 9545
          background: true
      - run:
          name: run test
          command: npm test 
      - slack/notify:
          fail_only: true
          color: '#42e2f4'
#          mentions: 'USERID1,USERID2,'
          message: This is a custom message notification
#          webhook: webhook
